import { HotelApiResponse } from '../models/hotel.model';

const hotelApiResponseMockData: HotelApiResponse = {
  items: [
    {
      title: 'Example Hotel 1',
      address: {
        label: '123 Main St, Example City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'CA',
        state: 'California',
        countyCode: 'XYZ',
        county: 'Example County',
        city: 'Example City',
        district: 'Example District',
        street: 'Main St',
        postalCode: '12345',
        houseNumber: '123',
      },
      position: {
        lat: 25.7617,
        lng: -80.1918,
      },

      // {
      //   lat: 37.7749,
      //   lng: -122.4194,
      // },
      distance: 2.5,
    },
    {
      title: 'Example Hotel 2',
      position: {
        lat: 40.7128,
        lng: -74.006,
      },
      address: {
        label: '456 Oak Ave, Another City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'NY',
        state: 'New York',
        countyCode: 'ABC',
        county: 'Another County',
        city: 'Another City',
        district: 'Another District',
        street: 'Oak Ave',
        postalCode: '67890',
        houseNumber: '456',
      },
      distance: 5.3,
    },
    {
      title: 'Example Hotel 3',
      position: {
        lat: 32.7767,
        lng: -96.797,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 7.1,
    },
    {
      title: 'Example Hotel 5',
      position: {
        lat: 39.7392,
        lng: -104.9903,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 10.0,
    },
    {
      title: 'Example Hotel 6',
      position: {
        lat: 34.0522,
        lng: -118.2437,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 8.5,
    },
    {
      title: 'Example Hotel 7',
      position: {
        lat: 41.8781,
        lng: -87.6298,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 3.8,
    },
    {
      title: 'Example Hotel 8',
      position: {
        lat: 29.7604,
        lng: -95.3698,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 6.4,
    },
    {
      title: 'Example Hotel 9',
      position: {
        lat: 36.7783,
        lng: -119.4179,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 12.3,
    },
    {
      title: 'Example Hotel 10',
      position: {
        lat: 45.5051,
        lng: -122.675,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 15.7,
    },
    {
      title: 'Example Hotel 11',
      position: {
        lat: 33.4484,
        lng: -112.074,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 9.0,
    },
    {
      title: 'Example Hotel 12',
      position: {
        lat: 42.3601,
        lng: -71.0589,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 11.2,
    },
    {
      title: 'Example Hotel 13',
      position: {
        lat: 37.7749,
        lng: -122.4194,
      },
      address: {
        label: '789 Pine Rd, Third City, Country',
        countryCode: 'US',
        countryName: 'United States',
        stateCode: 'TX',
        state: 'Texas',
        countyCode: 'PQR',
        county: 'Third County',
        city: 'Third City',
        district: 'Third District',
        street: 'Pine Rd',
        postalCode: '54321',
        houseNumber: '789',
      },
      distance: 2.5,
    },
  ],
};

export default hotelApiResponseMockData;
